/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BatchStage {
  'id' : bigint,
  'startTime' : Time,
  'operatorNotes' : string,
  'endTime' : Time,
  'weightInKg' : bigint,
  'weightOutKg' : bigint,
  'stage' : ProcessStage,
  'batchId' : bigint,
  'machineId' : bigint,
}
export interface DashboardStats {
  'totalRawMaterialWeightAvailable' : bigint,
  'ringWarehouseStockKg' : bigint,
  'recentQualityTestPassRate' : bigint,
  'totalYarnInventoryWeight' : bigint,
  'oeWarehouseStockKg' : bigint,
  'totalActiveOrders' : bigint,
  'totalMachinesRunning' : bigint,
  'totalInwardTodayKg' : bigint,
}
export type InventoryStatus = { 'inStock' : null } |
  { 'dispatched' : null };
export interface InwardEntry {
  'id' : bigint,
  'receivedQty' : bigint,
  'inwardDate' : Time,
  'inwardNumber' : string,
  'vehicleNumber' : string,
  'purchaseOrderId' : bigint,
  'warehouse' : Warehouse,
  'materialName' : string,
  'remarks' : string,
}
export interface Machine {
  'id' : bigint,
  'status' : MachineStatus,
  'name' : string,
  'currentOrderId' : [] | [bigint],
  'machineNumber' : string,
  'machineType' : MachineType,
}
export type MachineStatus = { 'idle' : null } |
  { 'maintenance' : null } |
  { 'running' : null };
export type MachineType = { 'ringFrame' : null } |
  { 'combing' : null } |
  { 'blowroom' : null } |
  { 'carding' : null } |
  { 'roving' : null } |
  { 'winding' : null } |
  { 'drawing' : null };
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type ProcessStage = { 'qualityCheck' : null } |
  { 'combing' : null } |
  { 'finished' : null } |
  { 'blowroom' : null } |
  { 'carding' : null } |
  { 'roving' : null } |
  { 'winding' : null } |
  { 'ringSpinning' : null } |
  { 'drawing' : null };
export type ProductType = { 'carded' : null } |
  { 'combed' : null };
export interface ProductionLog {
  'id' : bigint,
  'date' : Time,
  'operatorName' : string,
  'shift' : Shift,
  'efficiencyPercent' : bigint,
  'machineId' : bigint,
  'quantityKg' : bigint,
}
export interface ProductionOrder {
  'id' : bigint,
  'status' : OrderStatus,
  'yarnCountNe' : bigint,
  'twistDirection' : TwistDirection,
  'productType' : ProductType,
  'lotNumber' : string,
  'targetDate' : Time,
  'orderNumber' : string,
  'quantityKg' : bigint,
}
export interface PurchaseOrder {
  'id' : bigint,
  'status' : PurchaseOrderStatus,
  'orderedQty' : bigint,
  'expectedDeliveryDate' : Time,
  'supplier' : string,
  'orderDate' : Time,
  'materialName' : string,
  'poNumber' : string,
}
export type PurchaseOrderStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'partiallyReceived' : null };
export interface QualityTest {
  'id' : bigint,
  'csp' : bigint,
  'evennessPercent' : bigint,
  'neps' : bigint,
  'pass' : boolean,
  'elongationPercent' : bigint,
  'thinPlaces' : bigint,
  'batchId' : bigint,
  'hairinessIndex' : bigint,
  'thickPlaces' : bigint,
}
export interface RawMaterial {
  'id' : bigint,
  'status' : RawMaterialStatus,
  'inwardEntryId' : [] | [bigint],
  'supplier' : string,
  'lotNumber' : string,
  'weightKg' : bigint,
  'grade' : string,
  'dateReceived' : Time,
  'warehouse' : Warehouse,
}
export type RawMaterialStatus = { 'available' : null } |
  { 'consumed' : null } |
  { 'inUse' : null };
export type Shift = { 'morning' : null } |
  { 'night' : null } |
  { 'afternoon' : null };
export type Time = bigint;
export type TwistDirection = { 's' : null } |
  { 'z' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Warehouse = { 'oeRawMaterial' : null } |
  { 'ringRawMaterial' : null };
export interface WarehouseStock {
  'totalQty' : bigint,
  'warehouse' : Warehouse,
  'materialName' : string,
}
export interface YarnInventory {
  'id' : bigint,
  'status' : InventoryStatus,
  'yarnCountNe' : bigint,
  'twistDirection' : TwistDirection,
  'quantityCones' : bigint,
  'lotNumber' : string,
  'weightKg' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBatchStage' : ActorMethod<
    [bigint, ProcessStage, bigint, bigint, bigint, Time, Time, string],
    bigint
  >,
  'addInwardEntry' : ActorMethod<
    [string, bigint, Time, string, bigint, Warehouse, string, string],
    bigint
  >,
  'addProductionLog' : ActorMethod<
    [Shift, Time, bigint, bigint, bigint, string],
    bigint
  >,
  'addQualityTest' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean],
    bigint
  >,
  'addRawMaterial' : ActorMethod<
    [string, string, string, bigint, Warehouse, [] | [bigint]],
    bigint
  >,
  'addYarnInventory' : ActorMethod<
    [string, bigint, TwistDirection, bigint, bigint, InventoryStatus],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProductionOrder' : ActorMethod<
    [
      string,
      string,
      ProductType,
      bigint,
      TwistDirection,
      bigint,
      Time,
      OrderStatus,
    ],
    bigint
  >,
  'createPurchaseOrder' : ActorMethod<
    [string, string, string, bigint, Time, Time],
    bigint
  >,
  'deleteBatchStage' : ActorMethod<[bigint], undefined>,
  'deleteInwardEntry' : ActorMethod<[bigint], undefined>,
  'deleteMachine' : ActorMethod<[bigint], undefined>,
  'deleteProductionLog' : ActorMethod<[bigint], undefined>,
  'deleteProductionOrder' : ActorMethod<[bigint], undefined>,
  'deletePurchaseOrder' : ActorMethod<[bigint], undefined>,
  'deleteQualityTest' : ActorMethod<[bigint], undefined>,
  'deleteRawMaterial' : ActorMethod<[bigint], undefined>,
  'deleteYarnInventory' : ActorMethod<[bigint], undefined>,
  'getAllBatchStages' : ActorMethod<[], Array<BatchStage>>,
  'getAllInwardEntries' : ActorMethod<[], Array<InwardEntry>>,
  'getAllMachines' : ActorMethod<[], Array<Machine>>,
  'getAllProductionLogs' : ActorMethod<[], Array<ProductionLog>>,
  'getAllProductionOrders' : ActorMethod<[], Array<ProductionOrder>>,
  'getAllPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getAllQualityTests' : ActorMethod<[], Array<QualityTest>>,
  'getAllRawMaterials' : ActorMethod<[], Array<RawMaterial>>,
  'getAllWarehouseStock' : ActorMethod<[], Array<WarehouseStock>>,
  'getAllYarnInventory' : ActorMethod<[], Array<YarnInventory>>,
  'getBatchStage' : ActorMethod<[bigint], [] | [BatchStage]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInwardEntriesByPO' : ActorMethod<[bigint], Array<InwardEntry>>,
  'getInwardEntry' : ActorMethod<[bigint], [] | [InwardEntry]>,
  'getMachine' : ActorMethod<[bigint], [] | [Machine]>,
  'getProductionLog' : ActorMethod<[bigint], [] | [ProductionLog]>,
  'getProductionOrder' : ActorMethod<[bigint], [] | [ProductionOrder]>,
  'getPurchaseOrder' : ActorMethod<[bigint], [] | [PurchaseOrder]>,
  'getQualityTest' : ActorMethod<[bigint], [] | [QualityTest]>,
  'getRawMaterial' : ActorMethod<[bigint], [] | [RawMaterial]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYarnInventory' : ActorMethod<[bigint], [] | [YarnInventory]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerMachine' : ActorMethod<
    [string, MachineType, string, MachineStatus, [] | [bigint]],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBatchStage' : ActorMethod<
    [bigint, bigint, ProcessStage, bigint, bigint, bigint, Time, Time, string],
    undefined
  >,
  'updateMachine' : ActorMethod<
    [bigint, string, MachineType, string, MachineStatus, [] | [bigint]],
    undefined
  >,
  'updateProductionLog' : ActorMethod<
    [bigint, Shift, Time, bigint, bigint, bigint, string],
    undefined
  >,
  'updateProductionOrder' : ActorMethod<
    [
      bigint,
      string,
      string,
      ProductType,
      bigint,
      TwistDirection,
      bigint,
      Time,
      OrderStatus,
    ],
    undefined
  >,
  'updatePurchaseOrder' : ActorMethod<
    [bigint, string, string, string, bigint, Time, Time],
    undefined
  >,
  'updateQualityTest' : ActorMethod<
    [
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      boolean,
    ],
    undefined
  >,
  'updateRawMaterial' : ActorMethod<
    [bigint, string, string, string, bigint, RawMaterialStatus, Warehouse],
    undefined
  >,
  'updateYarnInventory' : ActorMethod<
    [bigint, string, bigint, TwistDirection, bigint, bigint, InventoryStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];