/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserEntry {
    principal: Principal;
    role: UserRole;
}
export type Time = bigint;
export interface RawMaterial {
    id: bigint;
    status: RawMaterialStatus;
    inwardEntryId?: bigint;
    supplier: string;
    lotNumber: string;
    weightKg: bigint;
    grade: string;
    dateReceived: Time;
    warehouse: Warehouse;
}
export interface YarnOpeningStockRecord {
    id: bigint;
    yarnCountNe: bigint;
    createdAt: Time;
    productType: ProductType;
    lotNumber: string;
    weightKg: bigint;
    spinningUnit: SpinningUnit;
    endUse: EndUse;
}
export interface UserProfile {
    name: string;
    role: string;
    department: string;
}
export enum EndUse {
    tfo = "tfo",
    ground = "ground",
    pile = "pile",
    warp = "warp",
    weft = "weft"
}
export enum ProductType {
    lt = "lt",
    bamboo = "bamboo",
    polyester = "polyester",
    viscose = "viscose",
    carded = "carded",
    combed = "combed"
}
export enum RawMaterialStatus {
    available = "available",
    consumed = "consumed",
    inUse = "inUse"
}
export enum SpinningUnit {
    openend = "openend",
    ringSpinning = "ringSpinning"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Warehouse {
    oeRawMaterial = "oeRawMaterial",
    ringRawMaterial = "ringRawMaterial"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addRawMaterialOpeningStock(materialName: string, supplier: string, grade: string, weightKg: bigint, warehouse: Warehouse, date: Time): Promise<bigint>;
    addYarnOpeningStock(lotNumber: string, yarnCountNe: bigint, spinningUnit: SpinningUnit, productType: ProductType, endUse: EndUse, weightKg: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteRawMaterialOpeningStock(id: bigint): Promise<void>;
    deleteYarnOpeningStock(id: bigint): Promise<void>;
    getAllRawMaterialOpeningStock(): Promise<Array<RawMaterial>>;
    getAllRawMaterials(): Promise<Array<RawMaterial>>;
    getAllUsers(): Promise<Array<UserEntry>>;
    getAllYarnOpeningStock(): Promise<Array<YarnOpeningStockRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeUser(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateUserRole(user: Principal, newRole: UserRole): Promise<void>;
}
import type { EndUse as _EndUse, ProductType as _ProductType, RawMaterial as _RawMaterial, RawMaterialStatus as _RawMaterialStatus, SpinningUnit as _SpinningUnit, Time as _Time, UserEntry as _UserEntry, UserProfile as _UserProfile, UserRole as _UserRole, Warehouse as _Warehouse, YarnOpeningStockRecord as _YarnOpeningStockRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addRawMaterialOpeningStock(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Warehouse, arg5: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRawMaterialOpeningStock(arg0, arg1, arg2, arg3, to_candid_Warehouse_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRawMaterialOpeningStock(arg0, arg1, arg2, arg3, to_candid_Warehouse_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async addYarnOpeningStock(arg0: string, arg1: bigint, arg2: SpinningUnit, arg3: ProductType, arg4: EndUse, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addYarnOpeningStock(arg0, arg1, to_candid_SpinningUnit_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ProductType_n5(this._uploadFile, this._downloadFile, arg3), to_candid_EndUse_n7(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addYarnOpeningStock(arg0, arg1, to_candid_SpinningUnit_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ProductType_n5(this._uploadFile, this._downloadFile, arg3), to_candid_EndUse_n7(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteRawMaterialOpeningStock(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRawMaterialOpeningStock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRawMaterialOpeningStock(arg0);
            return result;
        }
    }
    async deleteYarnOpeningStock(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteYarnOpeningStock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteYarnOpeningStock(arg0);
            return result;
        }
    }
    async getAllRawMaterialOpeningStock(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRawMaterialOpeningStock();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRawMaterialOpeningStock();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRawMaterials(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRawMaterials();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRawMaterials();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllYarnOpeningStock(): Promise<Array<YarnOpeningStockRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllYarnOpeningStock();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllYarnOpeningStock();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_EndUse_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EndUse): EndUse {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_RawMaterialStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RawMaterialStatus): RawMaterialStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_RawMaterial_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RawMaterial): RawMaterial {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SpinningUnit_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SpinningUnit): SpinningUnit {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserEntry_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserEntry): UserEntry {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Warehouse_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Warehouse): Warehouse {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_YarnOpeningStockRecord_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _YarnOpeningStockRecord): YarnOpeningStockRecord {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RawMaterialStatus;
    inwardEntryId: [] | [bigint];
    supplier: string;
    lotNumber: string;
    weightKg: bigint;
    grade: string;
    dateReceived: _Time;
    warehouse: _Warehouse;
}): {
    id: bigint;
    status: RawMaterialStatus;
    inwardEntryId?: bigint;
    supplier: string;
    lotNumber: string;
    weightKg: bigint;
    grade: string;
    dateReceived: Time;
    warehouse: Warehouse;
} {
    return {
        id: value.id,
        status: from_candid_RawMaterialStatus_n14(_uploadFile, _downloadFile, value.status),
        inwardEntryId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.inwardEntryId)),
        supplier: value.supplier,
        lotNumber: value.lotNumber,
        weightKg: value.weightKg,
        grade: value.grade,
        dateReceived: value.dateReceived,
        warehouse: from_candid_Warehouse_n17(_uploadFile, _downloadFile, value.warehouse)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    role: _UserRole;
}): {
    principal: Principal;
    role: UserRole;
} {
    return {
        principal: value.principal,
        role: from_candid_UserRole_n22(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    yarnCountNe: bigint;
    createdAt: _Time;
    productType: _ProductType;
    lotNumber: string;
    weightKg: bigint;
    spinningUnit: _SpinningUnit;
    endUse: _EndUse;
}): {
    id: bigint;
    yarnCountNe: bigint;
    createdAt: Time;
    productType: ProductType;
    lotNumber: string;
    weightKg: bigint;
    spinningUnit: SpinningUnit;
    endUse: EndUse;
} {
    return {
        id: value.id,
        yarnCountNe: value.yarnCountNe,
        createdAt: value.createdAt,
        productType: from_candid_ProductType_n27(_uploadFile, _downloadFile, value.productType),
        lotNumber: value.lotNumber,
        weightKg: value.weightKg,
        spinningUnit: from_candid_SpinningUnit_n29(_uploadFile, _downloadFile, value.spinningUnit),
        endUse: from_candid_EndUse_n31(_uploadFile, _downloadFile, value.endUse)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: null;
} | {
    consumed: null;
} | {
    inUse: null;
}): RawMaterialStatus {
    return "available" in value ? RawMaterialStatus.available : "consumed" in value ? RawMaterialStatus.consumed : "inUse" in value ? RawMaterialStatus.inUse : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    oeRawMaterial: null;
} | {
    ringRawMaterial: null;
}): Warehouse {
    return "oeRawMaterial" in value ? Warehouse.oeRawMaterial : "ringRawMaterial" in value ? Warehouse.ringRawMaterial : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lt: null;
} | {
    bamboo: null;
} | {
    polyester: null;
} | {
    viscose: null;
} | {
    carded: null;
} | {
    combed: null;
}): ProductType {
    return "lt" in value ? ProductType.lt : "bamboo" in value ? ProductType.bamboo : "polyester" in value ? ProductType.polyester : "viscose" in value ? ProductType.viscose : "carded" in value ? ProductType.carded : "combed" in value ? ProductType.combed : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    openend: null;
} | {
    ringSpinning: null;
}): SpinningUnit {
    return "openend" in value ? SpinningUnit.openend : "ringSpinning" in value ? SpinningUnit.ringSpinning : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tfo: null;
} | {
    ground: null;
} | {
    pile: null;
} | {
    warp: null;
} | {
    weft: null;
}): EndUse {
    return "tfo" in value ? EndUse.tfo : "ground" in value ? EndUse.ground : "pile" in value ? EndUse.pile : "warp" in value ? EndUse.warp : "weft" in value ? EndUse.weft : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RawMaterial>): Array<RawMaterial> {
    return value.map((x)=>from_candid_RawMaterial_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserEntry>): Array<UserEntry> {
    return value.map((x)=>from_candid_UserEntry_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_YarnOpeningStockRecord>): Array<YarnOpeningStockRecord> {
    return value.map((x)=>from_candid_YarnOpeningStockRecord_n25(_uploadFile, _downloadFile, x));
}
function to_candid_EndUse_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EndUse): _EndUse {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_SpinningUnit_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpinningUnit): _SpinningUnit {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Warehouse_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Warehouse): _Warehouse {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Warehouse): {
    oeRawMaterial: null;
} | {
    ringRawMaterial: null;
} {
    return value == Warehouse.oeRawMaterial ? {
        oeRawMaterial: null
    } : value == Warehouse.ringRawMaterial ? {
        ringRawMaterial: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SpinningUnit): {
    openend: null;
} | {
    ringSpinning: null;
} {
    return value == SpinningUnit.openend ? {
        openend: null
    } : value == SpinningUnit.ringSpinning ? {
        ringSpinning: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): {
    lt: null;
} | {
    bamboo: null;
} | {
    polyester: null;
} | {
    viscose: null;
} | {
    carded: null;
} | {
    combed: null;
} {
    return value == ProductType.lt ? {
        lt: null
    } : value == ProductType.bamboo ? {
        bamboo: null
    } : value == ProductType.polyester ? {
        polyester: null
    } : value == ProductType.viscose ? {
        viscose: null
    } : value == ProductType.carded ? {
        carded: null
    } : value == ProductType.combed ? {
        combed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EndUse): {
    tfo: null;
} | {
    ground: null;
} | {
    pile: null;
} | {
    warp: null;
} | {
    weft: null;
} {
    return value == EndUse.tfo ? {
        tfo: null
    } : value == EndUse.ground ? {
        ground: null
    } : value == EndUse.pile ? {
        pile: null
    } : value == EndUse.warp ? {
        warp: null
    } : value == EndUse.weft ? {
        weft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
