/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface InwardEntry {
    id: bigint;
    receivedQty: bigint;
    inwardDate: Time;
    inwardNumber: string;
    vehicleNumber: string;
    purchaseOrderId: bigint;
    warehouse: Warehouse;
    materialName: string;
    remarks: string;
}
export type Time = bigint;
export interface RawMaterial {
    id: bigint;
    status: RawMaterialStatus;
    inwardEntryId?: bigint;
    supplier: string;
    lotNumber: string;
    weightKg: bigint;
    grade: string;
    dateReceived: Time;
    warehouse: Warehouse;
}
export interface WarehouseStock {
    totalQty: bigint;
    warehouse: Warehouse;
    materialName: string;
}
export interface QualityTest {
    id: bigint;
    csp: bigint;
    evennessPercent: bigint;
    neps: bigint;
    pass: boolean;
    elongationPercent: bigint;
    thinPlaces: bigint;
    batchId: bigint;
    hairinessIndex: bigint;
    thickPlaces: bigint;
}
export interface ProductionLog {
    id: bigint;
    date: Time;
    operatorName: string;
    shift: Shift;
    efficiencyPercent: bigint;
    machineId: bigint;
    quantityKg: bigint;
}
export interface Machine {
    id: bigint;
    status: MachineStatus;
    name: string;
    currentOrderId?: bigint;
    machineNumber: string;
    machineType: MachineType;
}
export interface YarnInventory {
    id: bigint;
    status: InventoryStatus;
    yarnCountNe: bigint;
    twistDirection: TwistDirection;
    quantityCones: bigint;
    lotNumber: string;
    weightKg: bigint;
}
export interface DashboardStats {
    totalRawMaterialWeightAvailable: bigint;
    ringWarehouseStockKg: bigint;
    recentQualityTestPassRate: bigint;
    totalYarnInventoryWeight: bigint;
    oeWarehouseStockKg: bigint;
    totalActiveOrders: bigint;
    totalMachinesRunning: bigint;
    totalInwardTodayKg: bigint;
}
export interface PurchaseOrder {
    id: bigint;
    status: PurchaseOrderStatus;
    orderedQty: bigint;
    expectedDeliveryDate: Time;
    supplier: string;
    orderDate: Time;
    materialName: string;
    poNumber: string;
}
export interface ProductionOrder {
    id: bigint;
    status: OrderStatus;
    yarnCountNe: bigint;
    twistDirection: TwistDirection;
    productType: ProductType;
    lotNumber: string;
    targetDate: Time;
    orderNumber: string;
    quantityKg: bigint;
}
export interface UserProfile {
    name: string;
    role: string;
    department: string;
}
export interface BatchStage {
    id: bigint;
    startTime: Time;
    operatorNotes: string;
    endTime: Time;
    weightInKg: bigint;
    weightOutKg: bigint;
    stage: ProcessStage;
    batchId: bigint;
    machineId: bigint;
}
export enum InventoryStatus {
    inStock = "inStock",
    dispatched = "dispatched"
}
export enum MachineStatus {
    idle = "idle",
    maintenance = "maintenance",
    running = "running"
}
export enum MachineType {
    ringFrame = "ringFrame",
    combing = "combing",
    blowroom = "blowroom",
    carding = "carding",
    roving = "roving",
    winding = "winding",
    drawing = "drawing"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum ProcessStage {
    qualityCheck = "qualityCheck",
    combing = "combing",
    finished = "finished",
    blowroom = "blowroom",
    carding = "carding",
    roving = "roving",
    winding = "winding",
    ringSpinning = "ringSpinning",
    drawing = "drawing"
}
export enum ProductType {
    carded = "carded",
    combed = "combed"
}
export enum PurchaseOrderStatus {
    closed = "closed",
    open = "open",
    partiallyReceived = "partiallyReceived"
}
export enum RawMaterialStatus {
    available = "available",
    consumed = "consumed",
    inUse = "inUse"
}
export enum Shift {
    morning = "morning",
    night = "night",
    afternoon = "afternoon"
}
export enum TwistDirection {
    s = "s",
    z = "z"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Warehouse {
    oeRawMaterial = "oeRawMaterial",
    ringRawMaterial = "ringRawMaterial"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBatchStage(batchId: bigint, stage: ProcessStage, weightInKg: bigint, weightOutKg: bigint, machineId: bigint, startTime: Time, endTime: Time, operatorNotes: string): Promise<bigint>;
    addInwardEntry(inwardNumber: string, purchaseOrderId: bigint, inwardDate: Time, materialName: string, receivedQty: bigint, warehouse: Warehouse, vehicleNumber: string, remarks: string): Promise<bigint>;
    addProductionLog(shift: Shift, date: Time, machineId: bigint, quantityKg: bigint, efficiencyPercent: bigint, operatorName: string): Promise<bigint>;
    addQualityTest(batchId: bigint, csp: bigint, elongationPercent: bigint, evennessPercent: bigint, thinPlaces: bigint, thickPlaces: bigint, neps: bigint, hairinessIndex: bigint, pass: boolean): Promise<bigint>;
    addRawMaterial(lotNumber: string, supplier: string, grade: string, weightKg: bigint, warehouse: Warehouse, inwardEntryId: bigint | null): Promise<bigint>;
    addYarnInventory(lotNumber: string, yarnCountNe: bigint, twistDirection: TwistDirection, quantityCones: bigint, weightKg: bigint, status: InventoryStatus): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProductionOrder(orderNumber: string, lotNumber: string, productType: ProductType, yarnCountNe: bigint, twistDirection: TwistDirection, quantityKg: bigint, targetDate: Time, status: OrderStatus): Promise<bigint>;
    createPurchaseOrder(poNumber: string, supplier: string, materialName: string, orderedQty: bigint, orderDate: Time, expectedDeliveryDate: Time): Promise<bigint>;
    deleteBatchStage(id: bigint): Promise<void>;
    deleteInwardEntry(id: bigint): Promise<void>;
    deleteMachine(id: bigint): Promise<void>;
    deleteProductionLog(id: bigint): Promise<void>;
    deleteProductionOrder(id: bigint): Promise<void>;
    deletePurchaseOrder(id: bigint): Promise<void>;
    deleteQualityTest(id: bigint): Promise<void>;
    deleteRawMaterial(id: bigint): Promise<void>;
    deleteYarnInventory(id: bigint): Promise<void>;
    getAllBatchStages(): Promise<Array<BatchStage>>;
    getAllInwardEntries(): Promise<Array<InwardEntry>>;
    getAllMachines(): Promise<Array<Machine>>;
    getAllProductionLogs(): Promise<Array<ProductionLog>>;
    getAllProductionOrders(): Promise<Array<ProductionOrder>>;
    getAllPurchaseOrders(): Promise<Array<PurchaseOrder>>;
    getAllQualityTests(): Promise<Array<QualityTest>>;
    getAllRawMaterials(): Promise<Array<RawMaterial>>;
    getAllWarehouseStock(): Promise<Array<WarehouseStock>>;
    getAllYarnInventory(): Promise<Array<YarnInventory>>;
    getBatchStage(id: bigint): Promise<BatchStage | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getInwardEntriesByPO(purchaseOrderId: bigint): Promise<Array<InwardEntry>>;
    getInwardEntry(id: bigint): Promise<InwardEntry | null>;
    getMachine(id: bigint): Promise<Machine | null>;
    getProductionLog(id: bigint): Promise<ProductionLog | null>;
    getProductionOrder(id: bigint): Promise<ProductionOrder | null>;
    getPurchaseOrder(id: bigint): Promise<PurchaseOrder | null>;
    getQualityTest(id: bigint): Promise<QualityTest | null>;
    getRawMaterial(id: bigint): Promise<RawMaterial | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getYarnInventory(id: bigint): Promise<YarnInventory | null>;
    isCallerAdmin(): Promise<boolean>;
    registerMachine(name: string, machineType: MachineType, machineNumber: string, status: MachineStatus, currentOrderId: bigint | null): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBatchStage(id: bigint, batchId: bigint, stage: ProcessStage, weightInKg: bigint, weightOutKg: bigint, machineId: bigint, startTime: Time, endTime: Time, operatorNotes: string): Promise<void>;
    updateMachine(id: bigint, name: string, machineType: MachineType, machineNumber: string, status: MachineStatus, currentOrderId: bigint | null): Promise<void>;
    updateProductionLog(id: bigint, shift: Shift, date: Time, machineId: bigint, quantityKg: bigint, efficiencyPercent: bigint, operatorName: string): Promise<void>;
    updateProductionOrder(id: bigint, orderNumber: string, lotNumber: string, productType: ProductType, yarnCountNe: bigint, twistDirection: TwistDirection, quantityKg: bigint, targetDate: Time, status: OrderStatus): Promise<void>;
    updatePurchaseOrder(id: bigint, poNumber: string, supplier: string, materialName: string, orderedQty: bigint, orderDate: Time, expectedDeliveryDate: Time): Promise<void>;
    updateQualityTest(id: bigint, batchId: bigint, csp: bigint, elongationPercent: bigint, evennessPercent: bigint, thinPlaces: bigint, thickPlaces: bigint, neps: bigint, hairinessIndex: bigint, pass: boolean): Promise<void>;
    updateRawMaterial(id: bigint, lotNumber: string, supplier: string, grade: string, weightKg: bigint, status: RawMaterialStatus, warehouse: Warehouse): Promise<void>;
    updateYarnInventory(id: bigint, lotNumber: string, yarnCountNe: bigint, twistDirection: TwistDirection, quantityCones: bigint, weightKg: bigint, status: InventoryStatus): Promise<void>;
}
import type { BatchStage as _BatchStage, InventoryStatus as _InventoryStatus, InwardEntry as _InwardEntry, Machine as _Machine, MachineStatus as _MachineStatus, MachineType as _MachineType, OrderStatus as _OrderStatus, ProcessStage as _ProcessStage, ProductType as _ProductType, ProductionLog as _ProductionLog, ProductionOrder as _ProductionOrder, PurchaseOrder as _PurchaseOrder, PurchaseOrderStatus as _PurchaseOrderStatus, QualityTest as _QualityTest, RawMaterial as _RawMaterial, RawMaterialStatus as _RawMaterialStatus, Shift as _Shift, Time as _Time, TwistDirection as _TwistDirection, UserProfile as _UserProfile, UserRole as _UserRole, Warehouse as _Warehouse, WarehouseStock as _WarehouseStock, YarnInventory as _YarnInventory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBatchStage(arg0: bigint, arg1: ProcessStage, arg2: bigint, arg3: bigint, arg4: bigint, arg5: Time, arg6: Time, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBatchStage(arg0, to_candid_ProcessStage_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBatchStage(arg0, to_candid_ProcessStage_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addInwardEntry(arg0: string, arg1: bigint, arg2: Time, arg3: string, arg4: bigint, arg5: Warehouse, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInwardEntry(arg0, arg1, arg2, arg3, arg4, to_candid_Warehouse_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInwardEntry(arg0, arg1, arg2, arg3, arg4, to_candid_Warehouse_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async addProductionLog(arg0: Shift, arg1: Time, arg2: bigint, arg3: bigint, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProductionLog(to_candid_Shift_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProductionLog(to_candid_Shift_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addQualityTest(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQualityTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQualityTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addRawMaterial(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Warehouse, arg5: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRawMaterial(arg0, arg1, arg2, arg3, to_candid_Warehouse_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRawMaterial(arg0, arg1, arg2, arg3, to_candid_Warehouse_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addYarnInventory(arg0: string, arg1: bigint, arg2: TwistDirection, arg3: bigint, arg4: bigint, arg5: InventoryStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addYarnInventory(arg0, arg1, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_InventoryStatus_n10(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addYarnInventory(arg0, arg1, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg2), arg3, arg4, to_candid_InventoryStatus_n10(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProductionOrder(arg0: string, arg1: string, arg2: ProductType, arg3: bigint, arg4: TwistDirection, arg5: bigint, arg6: Time, arg7: OrderStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProductionOrder(arg0, arg1, to_candid_ProductType_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_OrderStatus_n16(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProductionOrder(arg0, arg1, to_candid_ProductType_n14(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_OrderStatus_n16(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async createPurchaseOrder(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: Time, arg5: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPurchaseOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPurchaseOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteBatchStage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBatchStage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBatchStage(arg0);
            return result;
        }
    }
    async deleteInwardEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInwardEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInwardEntry(arg0);
            return result;
        }
    }
    async deleteMachine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMachine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMachine(arg0);
            return result;
        }
    }
    async deleteProductionLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductionLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductionLog(arg0);
            return result;
        }
    }
    async deleteProductionOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductionOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductionOrder(arg0);
            return result;
        }
    }
    async deletePurchaseOrder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePurchaseOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePurchaseOrder(arg0);
            return result;
        }
    }
    async deleteQualityTest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQualityTest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQualityTest(arg0);
            return result;
        }
    }
    async deleteRawMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRawMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRawMaterial(arg0);
            return result;
        }
    }
    async deleteYarnInventory(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteYarnInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteYarnInventory(arg0);
            return result;
        }
    }
    async getAllBatchStages(): Promise<Array<BatchStage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBatchStages();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBatchStages();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInwardEntries(): Promise<Array<InwardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInwardEntries();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInwardEntries();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMachines(): Promise<Array<Machine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMachines();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMachines();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductionLogs(): Promise<Array<ProductionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductionLogs();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductionLogs();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductionOrders(): Promise<Array<ProductionOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductionOrders();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductionOrders();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPurchaseOrders(): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchaseOrders();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchaseOrders();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQualityTests(): Promise<Array<QualityTest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQualityTests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQualityTests();
            return result;
        }
    }
    async getAllRawMaterials(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRawMaterials();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRawMaterials();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWarehouseStock(): Promise<Array<WarehouseStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWarehouseStock();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWarehouseStock();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllYarnInventory(): Promise<Array<YarnInventory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllYarnInventory();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllYarnInventory();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBatchStage(arg0: bigint): Promise<BatchStage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBatchStage(arg0);
                return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBatchStage(arg0);
            return from_candid_opt_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n70(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n70(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInwardEntriesByPO(arg0: bigint): Promise<Array<InwardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInwardEntriesByPO(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInwardEntriesByPO(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInwardEntry(arg0: bigint): Promise<InwardEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInwardEntry(arg0);
                return from_candid_opt_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInwardEntry(arg0);
            return from_candid_opt_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMachine(arg0: bigint): Promise<Machine | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMachine(arg0);
                return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMachine(arg0);
            return from_candid_opt_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionLog(arg0: bigint): Promise<ProductionLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionLog(arg0);
                return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionLog(arg0);
            return from_candid_opt_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductionOrder(arg0: bigint): Promise<ProductionOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductionOrder(arg0);
                return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductionOrder(arg0);
            return from_candid_opt_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchaseOrder(arg0: bigint): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchaseOrder(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchaseOrder(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQualityTest(arg0: bigint): Promise<QualityTest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQualityTest(arg0);
                return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQualityTest(arg0);
            return from_candid_opt_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRawMaterial(arg0: bigint): Promise<RawMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawMaterial(arg0);
                return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawMaterial(arg0);
            return from_candid_opt_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async getYarnInventory(arg0: bigint): Promise<YarnInventory | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getYarnInventory(arg0);
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getYarnInventory(arg0);
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerMachine(arg0: string, arg1: MachineType, arg2: string, arg3: MachineStatus, arg4: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerMachine(arg0, to_candid_MachineType_n80(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_MachineStatus_n82(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerMachine(arg0, to_candid_MachineType_n80(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_MachineStatus_n82(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBatchStage(arg0: bigint, arg1: bigint, arg2: ProcessStage, arg3: bigint, arg4: bigint, arg5: bigint, arg6: Time, arg7: Time, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBatchStage(arg0, arg1, to_candid_ProcessStage_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBatchStage(arg0, arg1, to_candid_ProcessStage_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateMachine(arg0: bigint, arg1: string, arg2: MachineType, arg3: string, arg4: MachineStatus, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMachine(arg0, arg1, to_candid_MachineType_n80(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MachineStatus_n82(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMachine(arg0, arg1, to_candid_MachineType_n80(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_MachineStatus_n82(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateProductionLog(arg0: bigint, arg1: Shift, arg2: Time, arg3: bigint, arg4: bigint, arg5: bigint, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductionLog(arg0, to_candid_Shift_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductionLog(arg0, to_candid_Shift_n5(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateProductionOrder(arg0: bigint, arg1: string, arg2: string, arg3: ProductType, arg4: bigint, arg5: TwistDirection, arg6: bigint, arg7: Time, arg8: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductionOrder(arg0, arg1, arg2, to_candid_ProductType_n14(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, to_candid_OrderStatus_n16(this._uploadFile, this._downloadFile, arg8));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductionOrder(arg0, arg1, arg2, to_candid_ProductType_n14(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, to_candid_OrderStatus_n16(this._uploadFile, this._downloadFile, arg8));
            return result;
        }
    }
    async updatePurchaseOrder(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: Time, arg6: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseOrder(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateQualityTest(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQualityTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQualityTest(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateRawMaterial(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: RawMaterialStatus, arg6: Warehouse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRawMaterial(arg0, arg1, arg2, arg3, arg4, to_candid_RawMaterialStatus_n84(this._uploadFile, this._downloadFile, arg5), to_candid_Warehouse_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRawMaterial(arg0, arg1, arg2, arg3, arg4, to_candid_RawMaterialStatus_n84(this._uploadFile, this._downloadFile, arg5), to_candid_Warehouse_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateYarnInventory(arg0: bigint, arg1: string, arg2: bigint, arg3: TwistDirection, arg4: bigint, arg5: bigint, arg6: InventoryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateYarnInventory(arg0, arg1, arg2, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_InventoryStatus_n10(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateYarnInventory(arg0, arg1, arg2, to_candid_TwistDirection_n8(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_InventoryStatus_n10(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_BatchStage_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BatchStage): BatchStage {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryStatus_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryStatus): InventoryStatus {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_InwardEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InwardEntry): InwardEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_MachineStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MachineStatus): MachineStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_MachineType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MachineType): MachineType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Machine_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Machine): Machine {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_ProcessStage_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessStage): ProcessStage {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProductType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductType): ProductType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ProductionLog_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductionLog): ProductionLog {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_ProductionOrder_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductionOrder): ProductionOrder {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrderStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrderStatus): PurchaseOrderStatus {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseOrder_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseOrder): PurchaseOrder {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_RawMaterialStatus_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RawMaterialStatus): RawMaterialStatus {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_RawMaterial_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RawMaterial): RawMaterial {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Shift_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shift): Shift {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_TwistDirection_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TwistDirection): TwistDirection {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n71(_uploadFile, _downloadFile, value);
}
function from_candid_WarehouseStock_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WarehouseStock): WarehouseStock {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Warehouse_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Warehouse): Warehouse {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_YarnInventory_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _YarnInventory): YarnInventory {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BatchStage]): BatchStage | null {
    return value.length === 0 ? null : from_candid_BatchStage_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InwardEntry]): InwardEntry | null {
    return value.length === 0 ? null : from_candid_InwardEntry_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Machine]): Machine | null {
    return value.length === 0 ? null : from_candid_Machine_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductionLog]): ProductionLog | null {
    return value.length === 0 ? null : from_candid_ProductionLog_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductionOrder]): ProductionOrder | null {
    return value.length === 0 ? null : from_candid_ProductionOrder_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PurchaseOrder]): PurchaseOrder | null {
    return value.length === 0 ? null : from_candid_PurchaseOrder_n51(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QualityTest]): QualityTest | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RawMaterial]): RawMaterial | null {
    return value.length === 0 ? null : from_candid_RawMaterial_n56(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_YarnInventory]): YarnInventory | null {
    return value.length === 0 ? null : from_candid_YarnInventory_n64(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    startTime: _Time;
    operatorNotes: string;
    endTime: _Time;
    weightInKg: bigint;
    weightOutKg: bigint;
    stage: _ProcessStage;
    batchId: bigint;
    machineId: bigint;
}): {
    id: bigint;
    startTime: Time;
    operatorNotes: string;
    endTime: Time;
    weightInKg: bigint;
    weightOutKg: bigint;
    stage: ProcessStage;
    batchId: bigint;
    machineId: bigint;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        operatorNotes: value.operatorNotes,
        endTime: value.endTime,
        weightInKg: value.weightInKg,
        weightOutKg: value.weightOutKg,
        stage: from_candid_ProcessStage_n21(_uploadFile, _downloadFile, value.stage),
        batchId: value.batchId,
        machineId: value.machineId
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    receivedQty: bigint;
    inwardDate: _Time;
    inwardNumber: string;
    vehicleNumber: string;
    purchaseOrderId: bigint;
    warehouse: _Warehouse;
    materialName: string;
    remarks: string;
}): {
    id: bigint;
    receivedQty: bigint;
    inwardDate: Time;
    inwardNumber: string;
    vehicleNumber: string;
    purchaseOrderId: bigint;
    warehouse: Warehouse;
    materialName: string;
    remarks: string;
} {
    return {
        id: value.id,
        receivedQty: value.receivedQty,
        inwardDate: value.inwardDate,
        inwardNumber: value.inwardNumber,
        vehicleNumber: value.vehicleNumber,
        purchaseOrderId: value.purchaseOrderId,
        warehouse: from_candid_Warehouse_n26(_uploadFile, _downloadFile, value.warehouse),
        materialName: value.materialName,
        remarks: value.remarks
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MachineStatus;
    name: string;
    currentOrderId: [] | [bigint];
    machineNumber: string;
    machineType: _MachineType;
}): {
    id: bigint;
    status: MachineStatus;
    name: string;
    currentOrderId?: bigint;
    machineNumber: string;
    machineType: MachineType;
} {
    return {
        id: value.id,
        status: from_candid_MachineStatus_n31(_uploadFile, _downloadFile, value.status),
        name: value.name,
        currentOrderId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.currentOrderId)),
        machineNumber: value.machineNumber,
        machineType: from_candid_MachineType_n34(_uploadFile, _downloadFile, value.machineType)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    date: _Time;
    operatorName: string;
    shift: _Shift;
    efficiencyPercent: bigint;
    machineId: bigint;
    quantityKg: bigint;
}): {
    id: bigint;
    date: Time;
    operatorName: string;
    shift: Shift;
    efficiencyPercent: bigint;
    machineId: bigint;
    quantityKg: bigint;
} {
    return {
        id: value.id,
        date: value.date,
        operatorName: value.operatorName,
        shift: from_candid_Shift_n39(_uploadFile, _downloadFile, value.shift),
        efficiencyPercent: value.efficiencyPercent,
        machineId: value.machineId,
        quantityKg: value.quantityKg
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    yarnCountNe: bigint;
    twistDirection: _TwistDirection;
    productType: _ProductType;
    lotNumber: string;
    targetDate: _Time;
    orderNumber: string;
    quantityKg: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    yarnCountNe: bigint;
    twistDirection: TwistDirection;
    productType: ProductType;
    lotNumber: string;
    targetDate: Time;
    orderNumber: string;
    quantityKg: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n44(_uploadFile, _downloadFile, value.status),
        yarnCountNe: value.yarnCountNe,
        twistDirection: from_candid_TwistDirection_n46(_uploadFile, _downloadFile, value.twistDirection),
        productType: from_candid_ProductType_n48(_uploadFile, _downloadFile, value.productType),
        lotNumber: value.lotNumber,
        targetDate: value.targetDate,
        orderNumber: value.orderNumber,
        quantityKg: value.quantityKg
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _PurchaseOrderStatus;
    orderedQty: bigint;
    expectedDeliveryDate: _Time;
    supplier: string;
    orderDate: _Time;
    materialName: string;
    poNumber: string;
}): {
    id: bigint;
    status: PurchaseOrderStatus;
    orderedQty: bigint;
    expectedDeliveryDate: Time;
    supplier: string;
    orderDate: Time;
    materialName: string;
    poNumber: string;
} {
    return {
        id: value.id,
        status: from_candid_PurchaseOrderStatus_n53(_uploadFile, _downloadFile, value.status),
        orderedQty: value.orderedQty,
        expectedDeliveryDate: value.expectedDeliveryDate,
        supplier: value.supplier,
        orderDate: value.orderDate,
        materialName: value.materialName,
        poNumber: value.poNumber
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RawMaterialStatus;
    inwardEntryId: [] | [bigint];
    supplier: string;
    lotNumber: string;
    weightKg: bigint;
    grade: string;
    dateReceived: _Time;
    warehouse: _Warehouse;
}): {
    id: bigint;
    status: RawMaterialStatus;
    inwardEntryId?: bigint;
    supplier: string;
    lotNumber: string;
    weightKg: bigint;
    grade: string;
    dateReceived: Time;
    warehouse: Warehouse;
} {
    return {
        id: value.id,
        status: from_candid_RawMaterialStatus_n58(_uploadFile, _downloadFile, value.status),
        inwardEntryId: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.inwardEntryId)),
        supplier: value.supplier,
        lotNumber: value.lotNumber,
        weightKg: value.weightKg,
        grade: value.grade,
        dateReceived: value.dateReceived,
        warehouse: from_candid_Warehouse_n26(_uploadFile, _downloadFile, value.warehouse)
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalQty: bigint;
    warehouse: _Warehouse;
    materialName: string;
}): {
    totalQty: bigint;
    warehouse: Warehouse;
    materialName: string;
} {
    return {
        totalQty: value.totalQty,
        warehouse: from_candid_Warehouse_n26(_uploadFile, _downloadFile, value.warehouse),
        materialName: value.materialName
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InventoryStatus;
    yarnCountNe: bigint;
    twistDirection: _TwistDirection;
    quantityCones: bigint;
    lotNumber: string;
    weightKg: bigint;
}): {
    id: bigint;
    status: InventoryStatus;
    yarnCountNe: bigint;
    twistDirection: TwistDirection;
    quantityCones: bigint;
    lotNumber: string;
    weightKg: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InventoryStatus_n66(_uploadFile, _downloadFile, value.status),
        yarnCountNe: value.yarnCountNe,
        twistDirection: from_candid_TwistDirection_n46(_uploadFile, _downloadFile, value.twistDirection),
        quantityCones: value.quantityCones,
        lotNumber: value.lotNumber,
        weightKg: value.weightKg
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qualityCheck: null;
} | {
    combing: null;
} | {
    finished: null;
} | {
    blowroom: null;
} | {
    carding: null;
} | {
    roving: null;
} | {
    winding: null;
} | {
    ringSpinning: null;
} | {
    drawing: null;
}): ProcessStage {
    return "qualityCheck" in value ? ProcessStage.qualityCheck : "combing" in value ? ProcessStage.combing : "finished" in value ? ProcessStage.finished : "blowroom" in value ? ProcessStage.blowroom : "carding" in value ? ProcessStage.carding : "roving" in value ? ProcessStage.roving : "winding" in value ? ProcessStage.winding : "ringSpinning" in value ? ProcessStage.ringSpinning : "drawing" in value ? ProcessStage.drawing : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    oeRawMaterial: null;
} | {
    ringRawMaterial: null;
}): Warehouse {
    return "oeRawMaterial" in value ? Warehouse.oeRawMaterial : "ringRawMaterial" in value ? Warehouse.ringRawMaterial : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idle: null;
} | {
    maintenance: null;
} | {
    running: null;
}): MachineStatus {
    return "idle" in value ? MachineStatus.idle : "maintenance" in value ? MachineStatus.maintenance : "running" in value ? MachineStatus.running : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ringFrame: null;
} | {
    combing: null;
} | {
    blowroom: null;
} | {
    carding: null;
} | {
    roving: null;
} | {
    winding: null;
} | {
    drawing: null;
}): MachineType {
    return "ringFrame" in value ? MachineType.ringFrame : "combing" in value ? MachineType.combing : "blowroom" in value ? MachineType.blowroom : "carding" in value ? MachineType.carding : "roving" in value ? MachineType.roving : "winding" in value ? MachineType.winding : "drawing" in value ? MachineType.drawing : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    night: null;
} | {
    afternoon: null;
}): Shift {
    return "morning" in value ? Shift.morning : "night" in value ? Shift.night : "afternoon" in value ? Shift.afternoon : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "inProgress" in value ? OrderStatus.inProgress : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    s: null;
} | {
    z: null;
}): TwistDirection {
    return "s" in value ? TwistDirection.s : "z" in value ? TwistDirection.z : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    carded: null;
} | {
    combed: null;
}): ProductType {
    return "carded" in value ? ProductType.carded : "combed" in value ? ProductType.combed : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    partiallyReceived: null;
}): PurchaseOrderStatus {
    return "closed" in value ? PurchaseOrderStatus.closed : "open" in value ? PurchaseOrderStatus.open : "partiallyReceived" in value ? PurchaseOrderStatus.partiallyReceived : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    available: null;
} | {
    consumed: null;
} | {
    inUse: null;
}): RawMaterialStatus {
    return "available" in value ? RawMaterialStatus.available : "consumed" in value ? RawMaterialStatus.consumed : "inUse" in value ? RawMaterialStatus.inUse : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: null;
} | {
    dispatched: null;
}): InventoryStatus {
    return "inStock" in value ? InventoryStatus.inStock : "dispatched" in value ? InventoryStatus.dispatched : value;
}
function from_candid_variant_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BatchStage>): Array<BatchStage> {
    return value.map((x)=>from_candid_BatchStage_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InwardEntry>): Array<InwardEntry> {
    return value.map((x)=>from_candid_InwardEntry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Machine>): Array<Machine> {
    return value.map((x)=>from_candid_Machine_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductionLog>): Array<ProductionLog> {
    return value.map((x)=>from_candid_ProductionLog_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductionOrder>): Array<ProductionOrder> {
    return value.map((x)=>from_candid_ProductionOrder_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseOrder>): Array<PurchaseOrder> {
    return value.map((x)=>from_candid_PurchaseOrder_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RawMaterial>): Array<RawMaterial> {
    return value.map((x)=>from_candid_RawMaterial_n56(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WarehouseStock>): Array<WarehouseStock> {
    return value.map((x)=>from_candid_WarehouseStock_n61(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_YarnInventory>): Array<YarnInventory> {
    return value.map((x)=>from_candid_YarnInventory_n64(_uploadFile, _downloadFile, x));
}
function to_candid_InventoryStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryStatus): _InventoryStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MachineStatus_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MachineStatus): _MachineStatus {
    return to_candid_variant_n83(_uploadFile, _downloadFile, value);
}
function to_candid_MachineType_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MachineType): _MachineType {
    return to_candid_variant_n81(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_ProcessStage_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProcessStage): _ProcessStage {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProductType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): _ProductType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_RawMaterialStatus_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RawMaterialStatus): _RawMaterialStatus {
    return to_candid_variant_n85(_uploadFile, _downloadFile, value);
}
function to_candid_Shift_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shift): _Shift {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TwistDirection_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TwistDirection): _TwistDirection {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Warehouse_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Warehouse): _Warehouse {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryStatus): {
    inStock: null;
} | {
    dispatched: null;
} {
    return value == InventoryStatus.inStock ? {
        inStock: null
    } : value == InventoryStatus.dispatched ? {
        dispatched: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductType): {
    carded: null;
} | {
    combed: null;
} {
    return value == ProductType.carded ? {
        carded: null
    } : value == ProductType.combed ? {
        combed: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProcessStage): {
    qualityCheck: null;
} | {
    combing: null;
} | {
    finished: null;
} | {
    blowroom: null;
} | {
    carding: null;
} | {
    roving: null;
} | {
    winding: null;
} | {
    ringSpinning: null;
} | {
    drawing: null;
} {
    return value == ProcessStage.qualityCheck ? {
        qualityCheck: null
    } : value == ProcessStage.combing ? {
        combing: null
    } : value == ProcessStage.finished ? {
        finished: null
    } : value == ProcessStage.blowroom ? {
        blowroom: null
    } : value == ProcessStage.carding ? {
        carding: null
    } : value == ProcessStage.roving ? {
        roving: null
    } : value == ProcessStage.winding ? {
        winding: null
    } : value == ProcessStage.ringSpinning ? {
        ringSpinning: null
    } : value == ProcessStage.drawing ? {
        drawing: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Warehouse): {
    oeRawMaterial: null;
} | {
    ringRawMaterial: null;
} {
    return value == Warehouse.oeRawMaterial ? {
        oeRawMaterial: null
    } : value == Warehouse.ringRawMaterial ? {
        ringRawMaterial: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shift): {
    morning: null;
} | {
    night: null;
} | {
    afternoon: null;
} {
    return value == Shift.morning ? {
        morning: null
    } : value == Shift.night ? {
        night: null
    } : value == Shift.afternoon ? {
        afternoon: null
    } : value;
}
function to_candid_variant_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MachineType): {
    ringFrame: null;
} | {
    combing: null;
} | {
    blowroom: null;
} | {
    carding: null;
} | {
    roving: null;
} | {
    winding: null;
} | {
    drawing: null;
} {
    return value == MachineType.ringFrame ? {
        ringFrame: null
    } : value == MachineType.combing ? {
        combing: null
    } : value == MachineType.blowroom ? {
        blowroom: null
    } : value == MachineType.carding ? {
        carding: null
    } : value == MachineType.roving ? {
        roving: null
    } : value == MachineType.winding ? {
        winding: null
    } : value == MachineType.drawing ? {
        drawing: null
    } : value;
}
function to_candid_variant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MachineStatus): {
    idle: null;
} | {
    maintenance: null;
} | {
    running: null;
} {
    return value == MachineStatus.idle ? {
        idle: null
    } : value == MachineStatus.maintenance ? {
        maintenance: null
    } : value == MachineStatus.running ? {
        running: null
    } : value;
}
function to_candid_variant_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RawMaterialStatus): {
    available: null;
} | {
    consumed: null;
} | {
    inUse: null;
} {
    return value == RawMaterialStatus.available ? {
        available: null
    } : value == RawMaterialStatus.consumed ? {
        consumed: null
    } : value == RawMaterialStatus.inUse ? {
        inUse: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TwistDirection): {
    s: null;
} | {
    z: null;
} {
    return value == TwistDirection.s ? {
        s: null
    } : value == TwistDirection.z ? {
        z: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
